### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by pdonias** [nodef/chartist-svg#8]
Hi, I'm trying to test the README example but I'm getting the following error:
```js
const {createSVGWindow} = require('svgdom');
                          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/chartist-svg-issue/node_modules/svgdom/main-module.js from /tmp/chartist-svg-issue/node_modules/svgdom-css/index.js not supported.
Instead change the require of main-module.js in /tmp/chartist-svg-issue/node_modules/svgdom-css/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/tmp/chartist-svg-issue/node_modules/svgdom-css/index.js:2:27)
    at Object.<anonymous> (/tmp/chartist-svg-issue/node_modules/chartist-svg/index.js:2:19)
    at Object.<anonymous> (/tmp/chartist-svg-issue/index.js:2:21) {
  code: 'ERR_REQUIRE_ESM'
}
```

Node v18.18.2

**Comment by wolfram77** [comment]
If i understand, either need to use a dynamic import for svgdom or need to use a non-esm version of svgdom. I will get back to you in some time.

**Comment by wolfram77** [comment]
I stick to non-ESM version of svgdom package - this seems to resolve the issue. Just a setting the version number. When trying again remeber to fix/delete package-lock and node_modules.
